#!/usr/bin/env node
'use strict';

/**
 * regenerate_manifest.js
 *
 * Keeps analysis_results.html's run picker in sync with whatever dated
 * analysis exports actually exist on disk, so nobody has to hand-edit
 * manifest.json when a new weekly Connect_Analysis_<YYYY-MM-DD>.json shows up.
 *
 * What it does:
 *   1. Scans this folder for Connect_Analysis_<YYYY-MM-DD>.json files (and
 *      runs/<YYYY-MM-DD>.json as a secondary source, in case the R pipeline
 *      only drops files there).
 *   2. Rewrites manifest.json with every run found, newest first.
 *   3. Copies the newest run's file over connect_analysis/latest.json, so the
 *      default "Latest" view is guaranteed to match the newest dated file
 *      even if the pipeline forgets to update latest.json itself.
 *
 * Run it directly after dropping in a new export:
 *   node connect/connect_analysis/regenerate_manifest.js
 *
 * It also runs automatically at the top of deploy_hosting.js, so a normal
 * deploy always ships an up-to-date manifest.
 */

const fs = require('fs');
const path = require('path');

const DATE_RE = /^Connect_Analysis_(\d{4}-\d{2}-\d{2})\.json$/;
const RUNS_DATE_RE = /^(\d{4}-\d{2}-\d{2})\.json$/;

function regenerate(dir = __dirname) {
    const byDate = new Map();

    for (const name of safeReaddir(dir)) {
        const m = name.match(DATE_RE);
        if (m) byDate.set(m[1], { run_date: m[1], file: name });
    }

    // Fill in any dates only present under runs/<date>.json (Firebase-mirror
    // shape) that don't already have a Connect_Analysis_<date>.json copy.
    const runsDir = path.join(dir, 'runs');
    for (const name of safeReaddir(runsDir)) {
        const m = name.match(RUNS_DATE_RE);
        if (m && !byDate.has(m[1])) byDate.set(m[1], { run_date: m[1], file: `runs/${name}` });
    }

    const runs = [...byDate.values()].sort((a, b) => b.run_date.localeCompare(a.run_date));

    if (!runs.length) {
        console.warn('[regenerate_manifest] No dated analysis files found — leaving manifest.json/latest.json untouched.');
        return null;
    }

    const manifest = {
        _comment: "Auto-generated by regenerate_manifest.js (also runs automatically from deploy_hosting.js) from the dated analysis files in this folder. Don't hand-edit this — just drop in a new Connect_Analysis_<YYYY-MM-DD>.json and re-run/redeploy.",
        runs,
    };
    fs.writeFileSync(path.join(dir, 'manifest.json'), JSON.stringify(manifest, null, 2) + '\n');

    const newest = runs[0];
    fs.copyFileSync(path.join(dir, newest.file), path.join(dir, 'latest.json'));

    console.log(`[regenerate_manifest] manifest.json + latest.json refreshed — ${runs.length} run${runs.length === 1 ? '' : 's'}, newest: ${newest.run_date}`);
    return runs;
}

function safeReaddir(dir) {
    try { return fs.readdirSync(dir); } catch { return []; }
}

module.exports = { regenerate };

if (require.main === module) regenerate();
