#!/usr/bin/env node
'use strict';

/**
 * regenerate_manifest.js
 *
 * Keeps analysis_results.html's run picker in sync with whatever dated
 * analysis exports actually exist on disk, so nobody has to hand-edit
 * manifest.json when a new weekly Connect_Analysis_<YYYY-MM-DD>.json (or its
 * de-identified sibling) shows up.
 *
 * What it does, for BOTH the real (client-named) exports and the
 * de-identified exports used by demos/analysis_results.html:
 *   1. Scans this folder for Connect_Analysis_<YYYY-MM-DD>.json files (and
 *      runs/<YYYY-MM-DD>.json as a secondary source, in case the R pipeline
 *      only drops files there) to build manifest.json / latest.json.
 *   2. Scans this folder for Connect_Analysis_<YYYY-MM-DD>_deidentified.json
 *      files to build manifest_deidentified.json / latest_deidentified.json.
 *   3. Rewrites each manifest with every run found, newest first, and copies
 *      the newest run's file over the matching latest*.json, so the default
 *      "Latest" view always matches the newest dated file on disk even if
 *      the pipeline forgets to update latest*.json itself.
 *
 * Run it directly after dropping in new export(s) — real, de-identified, or
 * both:
 *   node connect/connect_analysis/regenerate_manifest.js
 *
 * It also runs automatically at the top of deploy_hosting.js, so a normal
 * deploy always ships up-to-date manifests.
 */

const fs = require('fs');
const path = require('path');

const DATE_RE = /^Connect_Analysis_(\d{4}-\d{2}-\d{2})\.json$/;
const DEIDENTIFIED_DATE_RE = /^Connect_Analysis_(\d{4}-\d{2}-\d{2})_deidentified\.json$/;
const RUNS_DATE_RE = /^(\d{4}-\d{2}-\d{2})\.json$/;

function buildManifest(dir, { manifestFile, latestFile, comment }, byDate) {
    const runs = [...byDate.values()].sort((a, b) => b.run_date.localeCompare(a.run_date));

    if (!runs.length) {
        console.warn(`[regenerate_manifest] No files found for ${manifestFile} — leaving ${manifestFile}/${latestFile} untouched.`);
        return null;
    }

    const manifest = { _comment: comment, runs };
    fs.writeFileSync(path.join(dir, manifestFile), JSON.stringify(manifest, null, 2) + '\n');

    const newest = runs[0];
    fs.copyFileSync(path.join(dir, newest.file), path.join(dir, latestFile));

    console.log(`[regenerate_manifest] ${manifestFile} + ${latestFile} refreshed — ${runs.length} run${runs.length === 1 ? '' : 's'}, newest: ${newest.run_date}`);
    return runs;
}

function regenerate(dir = __dirname) {
    const entries = safeReaddir(dir);
    const runsDirEntries = safeReaddir(path.join(dir, 'runs'));

    // ── Real (client-named) exports ──────────────────────────────────────
    const byDate = new Map();
    for (const name of entries) {
        const m = name.match(DATE_RE);
        if (m) byDate.set(m[1], { run_date: m[1], file: name });
    }
    // Fill in any dates only present under runs/<date>.json (Firebase-mirror
    // shape) that don't already have a Connect_Analysis_<date>.json copy.
    for (const name of runsDirEntries) {
        const m = name.match(RUNS_DATE_RE);
        if (m && !byDate.has(m[1])) byDate.set(m[1], { run_date: m[1], file: `runs/${name}` });
    }
    const realRuns = buildManifest(dir, {
        manifestFile: 'manifest.json',
        latestFile: 'latest.json',
        comment: "Auto-generated by regenerate_manifest.js (also runs automatically from deploy_hosting.js) from the dated analysis files in this folder. Don't hand-edit this — just drop in a new Connect_Analysis_<YYYY-MM-DD>.json and re-run/redeploy.",
    }, byDate);

    // ── De-identified exports (used by demos/analysis_results.html) ─────
    const byDateDeidentified = new Map();
    for (const name of entries) {
        const m = name.match(DEIDENTIFIED_DATE_RE);
        if (m) byDateDeidentified.set(m[1], { run_date: m[1], file: name });
    }
    const deidentifiedRuns = buildManifest(dir, {
        manifestFile: 'manifest_deidentified.json',
        latestFile: 'latest_deidentified.json',
        comment: "Auto-generated by regenerate_manifest.js (also runs automatically from deploy_hosting.js) from the dated *_deidentified.json files in this folder. Don't hand-edit this — just drop in a new Connect_Analysis_<YYYY-MM-DD>_deidentified.json and re-run/redeploy.",
    }, byDateDeidentified);

    if (!realRuns && !deidentifiedRuns) {
        console.warn('[regenerate_manifest] No dated analysis files of any kind found.');
        return null;
    }
    return { realRuns, deidentifiedRuns };
}

function safeReaddir(dir) {
    try { return fs.readdirSync(dir); } catch { return []; }
}

module.exports = { regenerate };

if (require.main === module) regenerate();
